version: "3.9"
services:

  db:
    image: "mgramin/pagila"
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"


  malewicz:
    build: ../.
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/config.toml:/app/config.toml
    depends_on:
      - db
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 3s
        max_attempts: 20
